kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 클러스터 이름을 지정합니다.
name: ckad-mockup
nodes:
- role: control-plane # 컨트롤 플레인 노드 1개
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
- role: worker       # 워커 노드 1개
- role: worker       # 워커 노드 1개
networking:
  # kindnetd CNI 비활성화
  disableDefaultCNI: true